parameters:
    uploads_dir: '%kernel.project_dir%/public/uploads'
    stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
    stripe_secret_key: '%env(STRIPE_SECRET_KEY)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Service\StripeService:
        arguments:
            $stripeSecretKey: '%stripe_secret_key%'   

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
